
server:
  port: 3309

spring:
  application:
    name: evaluation

#  redis:
#    host: 127.0.0.1
#    port: 6379
##    password: 123456
#    database: 0
#    timeout: 5000

  redis:
    port: 6379
    host: localhost

#  jedis:
#    pool:
#      max-idle: 500
#      min-idle: 50
#      max-wait: -1s
#      max-active: -1

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: '@cjx'
#    url: jdbc:mysql://localhost:3306/evasys?serverTimezone=GMT
#    username: 'root'
#    password: 'root'

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: 'ly'
    url: jdbc:mysql://localhost:3306/evasys?serverTimezone=GMT
    username: 'root'
    password: 'ly123'

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  main:
    #    banner-mode: off
    allow-circular-references: true

  files:
    upload:
      path: ../com/example/evaluation

mybatis-plus:
  type-aliases-package: com.example.domain
#  mapper-locations: classpath:/mappers/*.xml
#  type-enums-package: com.example.enums

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

