
server:
  port: 3309

spring:
  application:
    name: evaluation

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    database: 0
    timeout: 5000

  servlet:
    multipart:
      # 文件传输尺寸设置
      max-file-size: 1024MB
      max-request-size: 100240MB

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: '@cjx'
#    url: jdbc:mysql://localhost:3306/evasys?serverTimezone=GMT
#    username: 'root'
#    password: 'root'

# 远端数据配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: 'remote'
    url: jdbc:mysql://123.56.255.156:3306/evaluation?serverTimezone=Asia/Shanghai
    username: 'root'
    password: 'BJTU2023shixun@'
    hikari:
      connection-timeout: 10000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 5
      read-only: false

  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8

  main:
    #    banner-mode: off
    allow-circular-references: true

  mail:
    protocol: smtps
    host: smtp.qq.com
    username: 845796811@qq.com
    password: mytgnpzfynrcbded
    default-encoding: UTF-8

#  files:
#    upload:
#      path: classpath:/files
logging:
  level:
    com.fishpro.log: debug

mybatis-plus:
  type-aliases-package: com.example.domain
  mapper-locations: classpath:/mapper/*.xml
#  type-enums-package: com.example.enums

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

files:
  upload:
    path: C:\Users\84579\Desktop\shixun\BJTU-23Winter-MutualEvaluationSys\EvaluationBackend\evaluation\files\